travis:
  secure:
    BINSTAR_TOKEN: w+31nQZU+TylGVNc9AvIt/hIvq5pBP+/01TIjDN+iQnCxrK5uG8qYNd/erBaetBJZ97RNV+dXIHKd+PCI7ex9EsdFPa2nOhwTrIdTpK2+CuSv5LabPVhcNog3HmYIeTAhkzhFLn5DDUKiU5ErzX+aucZt74MLqvXiI010eeazSHnWnUV6iZbTOXpprNwf080O+DMdIIkpRZxCjSXHG7EVqXdWkxbf1V3gGbge1xX4zqeG9hlDc4b80UmyyGpcH70w0oiXdYypUajerYABJYOdD/KzHZ4YPDB/u6Qx1XCOqnIHEa8ssuTiX5aYM+TB668LpNtoPIEEMt/GdRIPBqPq5d73HUI76QjKAL3FeI7Wb08Xu0nZt5ZJ4VxyindnFX3GtdEBkROcjTPF3w5y1nJ1Jms7nitkUBIFZ3IBIEKCieMxaHaZY9+fKWKMgCEm93Wj6N+s1R+RGXwV1LNC2Xx60K9xgj76rQswzxt6CtksTtp7LSjKT/V9yVxG/vENqGzFu56Q8ERrQm1+51j/JC2LvQ0tLJhqzdMjr764uptA/IYHPxo0ulWiIa86u4m3xjKEDpe/ZTcutifpHvhTIZq02QfOYK6yRn0okyWzME/7k14rLfjHe11h4B5juW3m9NUcknnY8HOtyuOBOvLyLN6V9h/Y1uDUcdMfecclXbTeKY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
